
title: YangLab's Homepage
page-top-title: YangLabIDS
top-section-bg-text: Institute Of Data Science
home-subtitle: YangLab&ensp;|&ensp;YangLabIDS
copyright-text: '&copy; YangLabIDS 2023. All Rights Reserved.'
